<?php namespace Utils;
class Constants {
	const SOURCE_MYSQL_DISCOVERED = 1, SOURCE_MYSQL_CONVENTIONAL = 2, SOURCE_DOCTRINE2 = 3;
	const TARGET_NETTE_DATABASE = 1, TARGET_DOCTRINE2 = 2;
	const FOREIGN_KEYS_TABLE = 1, FOREIGN_KEYS_SELECT = 2;
	const TABLE_STATE_OK = 0, TABLE_STATE_ERROR_NO_PRIMARY_KEY = 1;
}